version: '3.8'

services:
  # Backend service - FastAPI
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: resume-optimizer-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    command: python main.py
    networks:
      - resume-optimizer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Frontend service - Next.js
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: resume-optimizer-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - resume-optimizer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  resume-optimizer-network:
    driver: bridge

volumes:
  node_modules:

